services:
  app:
    build: .
    network_mode: host
    environment:
      - DATASOURCE_JDBCURL=jdbc:postgresql://postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - app-logs:/app/logs
  postgres:
    image: postgres:17-alpine
    network_mode: host
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres-data:
  app-logs: