/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.rootbr.network.adapter.in.rest.api;

import com.rootbr.network.domain.port.rest.model.LoginPost500ResponseRestDto;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-05-04T22:50:29.295949+02:00[Europe/Berlin]", comments = "Generator version: 7.13.0")
@Validated
public interface FriendRestApi {

    /**
     * PUT /friend/delete/{user_id}
     *
     * @param userId  (required)
     * @return Пользователь успешно удалил из друзей пользователя (status code 200)
     *         or Невалидные данные ввода (status code 400)
     *         or Неавторизованный доступ (status code 401)
     *         or Ошибка сервера (status code 500)
     *         or Ошибка сервера (status code 503)
     */
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/friend/delete/{user_id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> friendDeleteUserIdPut(
         @PathVariable("user_id") String userId
    );


    /**
     * PUT /friend/set/{user_id}
     *
     * @param userId  (required)
     * @return Пользователь успешно указал своего друга (status code 200)
     *         or Невалидные данные ввода (status code 400)
     *         or Неавторизованный доступ (status code 401)
     *         or Ошибка сервера (status code 500)
     *         or Ошибка сервера (status code 503)
     */
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/friend/set/{user_id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> friendSetUserIdPut(
         @PathVariable("user_id") String userId
    );

}
