/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.rootbr.network.adapter.in.rest.api;

import com.rootbr.network.domain.port.rest.model.LoginPost200ResponseRestDto;
import com.rootbr.network.domain.port.rest.model.LoginPost500ResponseRestDto;
import com.rootbr.network.domain.port.rest.model.LoginPostRequestRestDto;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-05-04T22:50:29.295949+02:00[Europe/Berlin]", comments = "Generator version: 7.13.0")
@Validated
public interface LoginRestApi {

    /**
     * POST /login
     * Упрощенный процесс аутентификации путем передачи идентификатор пользователя и получения токена для дальнейшего прохождения авторизации
     *
     * @param loginPostRequestRestDto  (optional)
     * @return Успешная аутентификация (status code 200)
     *         or Невалидные данные (status code 400)
     *         or Пользователь не найден (status code 404)
     *         or Ошибка сервера (status code 500)
     *         or Ошибка сервера (status code 503)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/login",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<LoginPost200ResponseRestDto> loginPost(
         @Valid @RequestBody(required = false) LoginPostRequestRestDto loginPostRequestRestDto
    );

}
