dataSource:
  jdbcUrl: jdbc:postgresql://localhost:5432/social_network
  username: social_network
  password: social_network
  minimumIdle: 1

server:
  port: 8080
  backlog: 1000

auth:
  secret: yourStrongSecretKeyWithAtLeast32Characters
  expiration: 86400
  cost: 7