dataSource:
  jdbcUrl: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: postgres
  minimumIdle: 1

server:
  port: 8080
  backlog: 1000

auth:
  secret: yourStrongSecretKeyWithAtLeast32Characters
  expiration: 86400
  cost: 7