dataSource:
  jdbcUrl: jdbc:postgresql://localhost:5432/social_network
  username: social_network
  password: social_network
  minimumIdle: 10
  maximumPoolSize: 50
  connectionTimeout: 30000
  idleTimeout: 600000
  maxLifetime: 1800000
  leakDetectionThreshold: 60000

server:
  port: 8080
  backlog: 1000

auth:
  secret: yourStrongSecretKeyWithAtLeast32Characters
  expiration: 86400
  cost: 7